defaults: &defaults
  AMAZON_ACCESS_KEY: AKIAJJGUHCUAKNL2LYAQ
  AMAZON_SECRET_KEY: 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
  RECORDING_BUCKET: pshq-podcasts

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
