development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: the_pshq_entrepreneur_dev
  pool: 500
  host: localhost
  username: postgres
  password: password
  password: password

test:
    adapter: postgresql
    encoding: utf8
    reconnect: false
    database: the_pshq_entrepreneur_test
    pool: 5
    host: localhost
    username: postgres
    password: password
