ActiveRecord::Base.connection.execute("TRUNCATE TABLE comments;")
ActiveRecord::Base.connection.execute("TRUNCATE TABLE images;")
# ActiveRecord::Base.connection.execute("TRUNCATE TABLE podcasts;")
ActiveRecord::Base.connection.execute("TRUNCATE TABLE posts;")
ActiveRecord::Base.connection.execute("TRUNCATE TABLE users;")

user1 = User.where(:first_name => 'Samuel', :last_name => 'Davis', :email => 'samuel@problemsolutionhq.com').first_or_create(:password => 'password', :password_confirmation => 'password')
user2 = User.where(:first_name => 'Peter', :last_name => 'Sperry', :email => 'peter@problemsolutionhq.com').first_or_create(:password => 'password', :password_confirmation => 'password')
user3 = User.where(:first_name => 'Scott', :last_name => 'Davis', :email => 'scott@problemsolutionhq.com').first_or_create(:password => 'password', :password_confirmation => 'password')
user4 = User.where(:first_name => 'Phil', :last_name => 'Zelinger', :email => 'phil@problemsolutionhq.com').first_or_create(:password => 'password', :password_confirmation => 'password')
user5 = User.where(:first_name => 'Jake', :last_name => 'Davis', :email => 'jake@problemsolutionhq.com').first_or_create(:password => 'password', :password_confirmation => 'password')